const DATABASE_NAME='dining';
const USERNAME='root';
const PASSWORD='T123456t';
const HOST='localhost';
const  DIALECT='mysql';
module.exports = {
DATABASE_NAME: DATABASE_NAME,
USERNAME:USERNAME,
PASSWORD:PASSWORD,
HOST:HOST,
DIALECT:DIALECT
}